### ISSUE TITLE
Pong example crashes

### ISSUE THREAD

**Issue by crumblingstatue** [jeremyletang/rust-sfml#100]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5aeac8e in sf::Shader::bind(sf::Shader const*) ()
   from /usr/lib/libsfml-graphics.so.2.2.0
(gdb) bt
#0  0x00007ffff5aeac8e in sf::Shader::bind(sf::Shader const*) ()
   from /usr/lib/libsfml-graphics.so.2.2.0
#1  0x00007ffff5aea596 in sf::RenderTarget::draw(sf::Vertex const*, unsigned int, sf::PrimitiveType, sf::RenderStates const&) () from /usr/lib/libsfml-graphics.so.2.2.0
#2  0x00007ffff5af3a3c in sf::VertexArray::draw(sf::RenderTarget&, sf::RenderStates) const ()
   from /usr/lib/libsfml-graphics.so.2.2.0
#3  0x00007ffff5ae9e39 in sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&) ()
   from /usr/lib/libsfml-graphics.so.2.2.0
#4  0x00007ffff5af388c in sf::Text::draw(sf::RenderTarget&, sf::RenderStates) const ()
   from /usr/lib/libsfml-graphics.so.2.2.0
#5  0x00007ffff5ae9e39 in sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&) ()
   from /usr/lib/libsfml-graphics.so.2.2.0
#6  0x00007ffff75bb47c in sfRenderWindow_drawText () from /usr/lib/libcsfml-graphics.so.2.2
#7  0x00005555555769af in sfml::graphics::render_window::RenderWindow.RenderTarget::draw_text (
    self=0x7fffffffe320, text=0x7fffffffdf98, render_states=0x7fffffffd630)
    at src/graphics/render_window.rs:764
#8  0x00005555555601ba in pong::graphics::text::Text<'s>.Drawable::draw<sfml::graphics::render_window::RenderWindow> (self=0x7fffffffdf98, render_target=0x7fffffffe320, render_states=0x7fffffffd630)
    at src/graphics/text/mod.rs:329
#9  0x0000555555560161 in pong::graphics::render_window::RenderWindow.RenderTarget::draw<sfml::graphics::text::Text> (self=0x7fffffffe320, object=0x7fffffffdf98) at src/graphics/render_window.rs:734
#10 0x000055555555e684 in pong::main () at examples/pong.rs:243
#11 0x0000555555583489 in rust_try_inner ()
#12 0x0000555555583476 in rust_try ()
#13 0x0000555555580b44 in rt::lang_start::h35b1454095097ebdvFw ()
#14 0x0000555555560305 in main ()
```

**Comment by jeremyletang** [comment]
I cannot reproduce this on my computer.

**Comment by crumblingstatue** [comment]
I guess it's up to me then to track this down.

**Comment by crumblingstatue** [comment]
Okay, I had SFML 2.2 installed, and rust-sfml only supports SFML 2.1 right now.
I downgraded to SFML 2.1, and it works.

**Comment by jeremyletang** [comment]
I think we can let this open as we plan to support sfml 2.3 soon ?

**Comment by crumblingstatue** [comment]
I imagine we will carefully examine how the internals need to be updated to support SFML 2.3, so this issue will probably not arise if we update them correctly.
